server:
  port: 4060

spring:
  application:
    name: service-one  
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true 
    service-url:
      defaultZone: http://localhost:8761/eureka
        