info:
  app:
    name: ${spring.application.name}
  build:
    artifactId: '@project.artifact@'
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: srivatsan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update
  application:
    name: cibil-score-service
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  info:
    env:
      enabled: true
      
      